"""
the validator agent - the quality gate between SQL generation and execution.
this is SEPARATE from query_validator.py (which is a security gate).
this agent's job is semantic: "does this SQL query actually answer the question?"

it checks:
    1. semantic alignment  - does the SQL answer what was asked?
    2. schema correctness  - are the tables/columns real and used correctly?
    3. JOIN completeness   - are relationships properly joined?
    4. logic sanity        - right aggregations, filters, orderings?

if it rejects, it returns specific feedback so the SQL Agent can self-correct.
"""

import os
from core.llm import chat
from core.logger import get_logger


logger = get_logger(__name__)


def _build_validator_prompt(schema_prompt: str) -> str:
    return f"""You are a senior SQL validation expert embedded in an intelligent Text-to-SQL system.

This system serves non-technical business users — stakeholders, analysts, and decision-makers — who ask
questions in plain English and expect accurate answers from their relational databases. They have no SQL
knowledge. If a wrong query reaches the database, they will receive a wrong or misleading answer with no
way to know. Your validation is the last line of defence before execution.

The system supports PostgreSQL, SQLite, and MySQL. Queries must be read-only SELECT statements only.

You are given:
  - The user's original natural language question
  - The SQL query generated by the SQL Agent
  - The full database schema (as CREATE TABLE statements with sample rows)

{schema_prompt}

YOUR JOB:
Determine whether the generated SQL query will correctly and completely answer the user's question.
Be thorough. A query that returns results but answers the wrong question is a failure.

EVALUATE ACROSS THESE FIVE DIMENSIONS:

1. SEMANTIC ALIGNMENT
   Does the SQL answer exactly what the user asked — nothing more, nothing less?
   Watch for: answering a related but different question, missing the core intent,
   returning too much or too little scope.

2. SCHEMA CORRECTNESS
   Are all referenced table names and column names real and spelled correctly per the schema?
   Are the correct tables being queried for the data the user is asking about?
   Watch for: hallucinated column names, wrong table for the data, case sensitivity issues.

3. JOIN COMPLETENESS
   If data from multiple tables is needed, are all necessary JOINs present?
   Are JOIN conditions using the correct foreign key relationships defined in the schema?
   Watch for: missing JOINs that would cause cross products, wrong join columns,
   joining on the wrong keys.

4. LOGIC ACCURACY
   Are aggregations (COUNT, SUM, AVG), filters (WHERE), groupings (GROUP BY),
   orderings (ORDER BY), and limits (LIMIT) correct for what was asked?
   Watch for: missing GROUP BY when aggregating, wrong filter values,
   DESC/ASC confusion, off-by-one limits.

5. EDGE CASE HANDLING
   Would this query behave correctly if some values are NULL or some records are missing?
   Watch for: unguarded NULLs in filters or joins that could silently drop records.

RESPOND IN THIS EXACT FORMAT — no extra text before or after:

VERDICT: PASS or FAIL
REASON: <one concise sentence explaining the verdict>
FEEDBACK: <if FAIL — one specific, actionable instruction telling the SQL Agent exactly what to fix. If PASS — None>
"""


def validator_agent(question: str, sql: str, schema_prompt: str) -> dict:
    """
    validates whether the generated sql correctly answers the user's question.

    parameters
    ----------
    question      : the original natural language question
    sql           : the SQL query generated by the SQL Agent
    schema_prompt : the CREATE TABLE-style schema string

    returns
    -------
    {
        "status":   "ok" | "rejected" | "error",
        "reason":   str,
        "feedback": str | None
    }
    """
    system_prompt = _build_validator_prompt(schema_prompt)

    user_content = f"""Question: {question}

Generated SQL:
{sql}

Is this SQL correct and complete for the question?"""

    logger.debug("validator | running validation | question: %s", question)
    logger.debug("validator | sql to validate:\n%s", sql)

    try:
        raw = chat(
            system     = system_prompt,
            user       = user_content,
            max_tokens = 512,
            provider   = "anthropic",
            model      = "claude-sonnet-4-20250514",
        )

        verdict  = _extract_field(raw, "VERDICT")
        reason   = _extract_field(raw, "REASON")
        feedback = _extract_field(raw, "FEEDBACK")

        if verdict and "PASS" in verdict.upper():
            logger.info("validator | PASS | reason: %s", reason)
            return {
                "status":   "ok",
                "reason":   reason or "SQL is valid and answers the question.",
                "feedback": None,
            }
        else:
            logger.warning("validator | FAIL | reason: %s | feedback: %s", reason, feedback)
            return {
                "status":   "rejected",
                "reason":   reason or "SQL does not correctly answer the question.",
                "feedback": feedback or "Revisit the query logic and schema relationships.",
            }

    except Exception as e:
        # validator is unavailable — log the error so it can be investigated in production
        logger.error("validator | API error — validator unavailable: %s", str(e), exc_info=True)
        return {
            "status":   "error",
            "reason":   f"Validator encountered an error: {str(e)}",
            "feedback": None,
        }


def _extract_field(text: str, field: str) -> str | None:
    # extracts "FIELD: value" from the LLM response
    for line in text.splitlines():
        if line.strip().upper().startswith(f"{field}:"):
            return line.split(":", 1)[1].strip()
    return None